### PR TITLE
Fix GraalVM support

### PR DESCRIPTION
**Pull request by ilopmar**
This PR fixes this https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1881507137

@yawkat it seems that some of the graalvm changes you did for Netty in micronaut-core the other day are not playing well with the gRPC app. The CI passed the other day, but maybe with the new Netty version we need to do more things: 

I've removed unnecessary config in the client module but I needed to add more config to the server. Do you think we need to do it here or is it better to include this config in core?

### CODE REVIEW

**Comment by yawkat** [comment]
Why is the additional runtime init config for the server necessary? `NettyFeature` in core should make the entire `io.netty` package initialize at runtime. What makes that not work?

**Comment by ilopmar** [comment]
I think the problem is that the gRPC server app doesn't include `micronaut-http-netty`.

Running:

```
./gradlew server:dependencyInsight --dependency micronaut-http-netty --configuration=compileClasspath
```
Doesn't return anything.

Doing the same with the "basic-app" (or any app that uses Netty http server):

```
> Task :dependencyInsight
io.micronaut:micronaut-http-netty:3.2.2-SNAPSHOT
   variant "runtimeElements" [
      org.gradle.category            = library
      org.gradle.dependency.bundling = external
      org.gradle.jvm.version         = 8
      org.gradle.libraryelements     = jar
      org.gradle.usage               = java-runtime
      org.gradle.status              = integration (not requested)

      Requested attributes not found in the selected variant:
         org.gradle.jvm.environment     = standard-jvm
   ]
   Selection reasons:
      - By constraint
      - Forced

io.micronaut:micronaut-http-netty:3.2.2-SNAPSHOT
+--- io.micronaut:micronaut-bom:3.2.2-SNAPSHOT
|    \--- runtimeClasspath
+--- io.micronaut:micronaut-http-client:3.2.2-SNAPSHOT
|    +--- runtimeClasspath (requested io.micronaut:micronaut-http-client)
|    \--- io.micronaut:micronaut-bom:3.2.2-SNAPSHOT (*)
\--- io.micronaut:micronaut-http-server-netty:3.2.2-SNAPSHOT
     +--- runtimeClasspath (requested io.micronaut:micronaut-http-server-netty)
     \--- io.micronaut:micronaut-bom:3.2.2-SNAPSHOT (*)

(*) - dependencies omitted (listed previously)

```

**Comment by graemerocher** [comment]
I think it is because gRPC doesn't depend on `http-netty`

**Comment by ilopmar** [comment]
But it shouldn't depend on it, right?

**Comment by yawkat** [comment]
I see, that explains it. Then we need some way to get the NettyFeature into other projects that use netty as well. Maybe you could simply copy it to this project for now, and we can move it into a more generic package in core?

**Comment by graemerocher** [comment]
Well gRPC has nothing to do with the HTTP protocol so it doesn't logically make sense to add a dependency. What @yawkat said of having a netty module that isn't related to HTTP makes sense.

**Comment by ilopmar** [comment]
I've copied the class from core and use the string version of these classes: https://github.com/micronaut-projects/micronaut-grpc/pull/435/files#diff-1b80668bb3b018440b6a4d6a35414422a696e8846e58d556bc0facc95160cda7R53-R60 and it works

**Comment by yawkat** [comment]
ok, good. You could drop the `io.micronaut.http.*` references but it doesn't matter. I will open an issue in core to discuss how we can generalize this.

**Review by yawkat — APPROVED** [review]

**Pull request merged**
