### PR TITLE
Added protobuf bom to gradle libs. Libraries upgrade. Java 17

### PR DESCRIPTION
**Pull request by altro3**
This is copy of https://github.com/micronaut-projects/micronaut-grpc/pull/602 PR. 

Sorry, don't know what happened with my local repo and fork, but can't push changes to old PR. Problem only with this repo :-(

About changes: all problems with compatibility fixed, exclude one: can't build `test-suite-groovy`. Now you can't build this module:
изображение
As I understand, problem with compatibility protoc with groovy 4.0, but it is not exactly.

@wetted @sdelamo

### CODE REVIEW

**Comment by altro3** [comment]
If you run `gradle clean build -x test-suite-groovy:build` you'll see that all other tasks works fine.

**Comment by wetted** [comment]
> About changes: all problems with compatibility fixed, exclude one: can't build `test-suite-groovy`. Now you can't build this module: изображение As I understand, problem with compatibility protoc with groovy 4.0, but it is not exactly.
> 
> @wetted @sdelamo

Adding this to your build should resolve the collision between `codehaus` and `apache` groovy:

```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(module("org.codehaus.groovy:groovy"))
                .using(module("org.apache.groovy:groovy:4.0.6"))
    }
}
```

**Comment by altro3** [comment]
@wetted thanks! Yes, now it works, but after some my changes.

I do not understand what happened. but this module, after the mikronaut 4.0 transition, seemed to be disconnected from the general context. Here are some weird things I noticed:

1. This module now does not see the micronautVersion property, although it is specified in the parent project. All other submodules correctly see this property. I had to duplicate this property (micronautVersion=4.0.0-SNAPSHOT) in the submodule

2. This module also does not see the configuration settings for replacing the groove. That's why he had a conflict with the groove versions. I had to duplicate the block
```groovy
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(module("org.codehaus.groovy:groovy"))
                .using(module("org.apache.groovy:groovy:4.0.6"))
    }
}
```
3. This module cannot depend on other submodules, i.e. there was a dependency implementation(project(':grpc-server-runtime')) - but now it's an error.

And all these problems appeared only in this submug and only after connecting micronaut version 4.0.0-SNAPSHOT

**Comment by wetted** [comment]
@altro3 look here: https://github.com/micronaut-projects/micronaut-grpc/blob/e9b5da4f50b7516ebac324c7ab4a5f3d279e54e0/buildSrc/src/main/groovy/io.micronaut.build.internal.grpc-base.gradle#L17

The `4.0.x` branch has all the changes for building with Micronaut 4. The `master` branch is still targeting Micronaut 3. You PR needs to target the `4.0.x` branch for now. That should solve your build issues.

FYI: I will be on vacation until 14 Nov but @sdelamo or @timyates should be able to help you sort through build issues.

**Pull request merged**
