### PR TITLE
Move all modules to version catalog. Update lib versions. Added lost protobuf artifacts.

### LINKED ISSUE #786: Add com.google.protobuf:protobuf-kotlin to Micronaut BOM
### Feature description

The dependency "com.google.protobuf:protobuf-kotlin" currently seems to be missing from the Micronaut BOM. That means I have to write dependencies like this:

```
    implementation("com.google.protobuf:protobuf-java-util")
    implementation("com.google.protobuf:protobuf-kotlin:3.24.2")
```

... which is a bit unfortunate, since it is difficult to ensure the versions are aligned.

Could you add it?

### LINKED ISSUE #805: Micronaut 4.2.0 breaks grpc services
### Expected Behavior

GRPC serialization back to a client reply should work.

**NOTE: this does not happen in the projects below because the 3rd party patch was applied to them.  This allows the grpc services to work in micronaut 4.2.0. **

### Actual Behaviour

GRPC throws exceptions

## Examples

I have a number of simple grpc projects in my repo that run micronaut services.  Once I bumped the service to 4.2.0, the OOTB functionality no longer works for grpc blocking stubs and regular stubs.  Below are the URLs to the projects (there's one dependent project as well, which matches the grpc running version of 1.59.0.

The sample applications where this depends on grpc servers are as follows:
https://github.com/krickert/search_indexer/tree/master/services/grpc-services/grpc-nlp-service
https://github.com/krickert/search_indexer/tree/master/services/grpc-services/grpc-vectorizer-service
https://github.com/krickert/search_indexer/tree/master/services/pipeline-processor

The tests that break are any test that uses the standard grpc transport.

## Barebones test (follows the same as the guide docs)

Here is the most barebones test:

https://github.com/krickert/grpc_micronaut_420_broken_example

This uses jdk17 (amazon latest), maven 3.9.5 on the latest ubuntu desktop.  Also repeatable on jdk17 on osx.  Didn't test anywhere else yet since I see consistent results.

## output from test

```
[ERROR] com.broken.grpc.GrpcExampleTest.testServerEndpoint -- Time elapsed: 0.165 s <<< ERROR!
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
	at com.broken.grpc.GrpcExampleServiceGrpc$GrpcExampleServiceBlockingStub.send(GrpcExampleServiceGrpc.java:160)
	at com.broken.grpc.GrpcExampleTest.testServerEndpoint(GrpcExampleTest.java:79)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension$2.proceed(MicronautJunit5Extension.java:142)
	at io.micronaut.test.extensions.AbstractMicronautExtension.interceptEach(AbstractMicronautExtension.java:157)
	at io.micronaut.test.extensions.AbstractMicronautExtension.interceptTest(AbstractMicronautExtension.java:114)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.interceptTestMethod(MicronautJunit5Extension.java:129)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.UnsupportedOperationException
	at io.grpc.netty.AbstractHttp2Headers.isEmpty(AbstractHttp2Headers.java:40)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:419)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:352)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:56)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:476)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:484)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:253)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:188)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
The above is returned for the non-blocking test... 

The following is returned for the blocking test:
```
11:19:53.868 [io-executor-thread-2] ERROR com.broken.grpc.GrpcExampleTest - Not implemented
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.UnsupportedOperationException: null
	at io.grpc.netty.AbstractHttp2Headers.isEmpty(AbstractHttp2Headers.java:40)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:419)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:352)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:56)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:476)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:484)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:253)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:188)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

In both instances, the service is called, it seems the serialization is the broken part.

### Steps To Reproduce

1. Linux ubuntu
2. jdk17 / maven 3.9.5
3. `git clone https://github.com/krickert/grpc_micronaut_420_broken_example.git`
4. `cd grpc_micronaut_420_broken_example`
5. `mvn test`

### Environment Information

Latest ubuntu
jdk 17 
```
~/IdeaProjects/grpc_micronaut_420_broken_example$ java -version
openjdk version "17.0.9" 2023-10-17 LTS
OpenJDK Runtime Environment Corretto-17.0.9.8.1 (build 17.0.9+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.9.8.1 (build 17.0.9+8-LTS, mixed mode, sharing)
```

### Example Application

https://github.com/krickert/grpc_micronaut_420_broken_example

### Version

4.2.0

### PR DESCRIPTION
**Pull request by altro3**
Fixed #786
Fixed #805

### CODE REVIEW

**Comment by jeremyg484** [comment]
@altro3 Thanks for this, looks good to me. I pushed an additional small change to fix the broken test.

**Comment by altro3** [comment]
@jeremyg484 You ar ewelcome! I think also need to remove `micronaut-discovery-client = '4.1.0'` from versions catalog

**Comment by jeremyg484** [comment]
> @jeremyg484 You ar ewelcome! I think also need to remove `micronaut-discovery-client = '4.1.0'` from versions catalog

@altro3 We are still referencing it in the test-suite-* modules so it needs to stay for the moment. I think it might be safe to remove there as well, but need to sort that out separately.

**Comment by jeremyg484** [comment]
@altro3 I believe you've signed the CLA for this project previously, correct? I don't know why our CLA check is hanging at the moment.

**Review by jeremyg484 — APPROVED** [review]

**Comment by jeremyg484** [comment]
@sdelamo Amongst the other cleanup, this PR updates grpc-java to 1.59.1, which was released yesterday and contains the Netty fix we were waiting on. Once merged, it would clear the way for the other version upgrade PR's, such as to Micronaut Platform 4.2.0.

**Comment by altro3** [comment]
@jeremyg484 Yes, sure. Look to my work with micronaut ;-). I updated version of micronaut to 4.2.0 - now it works fine. Also I removed `protobufGradleVersion` and now this plugin connecting to example projectsby alias - `alias(libs.plugins.protobuf)`

**Pull request merged**
