### PR TITLE
Added protobuf bom to gradle libs. Libraries upgrade. Java 17

### PR DESCRIPTION
**Pull request by altro3**

### CODE REVIEW

**Review by wetted — CHANGES_REQUESTED** [review]
@altro3 I reviewed your changes on #596 before I knew you closed the issue. Please resolve my review comments from there and I will review this again. Thank you.

**Comment by altro3** [comment]
@wetted Fixed all, eclude micronaut-* prefixed libs. Could you help? When I try to change, for example,  `libs.micronaut.runtime` to `mn.runtime`, I see this exception:
изображение

**Review by wetted — APPROVED** [review]

**Comment by wetted** [comment]
ping @sdelamo 

This PR probably should have targeted this 4.0.x branch of this module, since that has some of my previous work, including removal of deprecations, but I know you're planning to merge that to master anyway. Do you want to do that first and then merge this (with maybe some minor conflicts) or target this to the 4.0.x branch.

**Comment by sdelamo** [comment]
@altro3 thanks for your PR. 

We are [working on a PR](https://github.com/micronaut-projects/micronaut-grpc/pull/607) to set `master` to be the branch pointing to 4..0.x

If you have changes, which you think should go to the next minor, the PR should point to the `3.4.x` branch. 

can you merge either branches 4.0.x or 3.4.x against this PR and change the base of this PR accordingly.

**Comment by altro3** [comment]
@sdelamo Hi! I rebased this PR. Here are changes only for issue https://github.com/micronaut-projects/micronaut-core/issues/8059. But there are two problems now:
1. Test `GrpcNamedChannelSpec test named client - eager init ` failed with exception:
```
  Message: No bean of type [io.micronaut.json.JsonMapper] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
  Path Taken: new DefaultNettyHttpClientRegistry(HttpClientConfiguration defaultHttpClientConfiguration,HttpClientFilterResolver httpClientFilterResolver,LoadBalancerResolver loadBalancerResolver,NettyClientSslBuilder nettyClientSslBuilder,ThreadFactory threadFactory,MediaTypeCodecRegistry codecRegistry,EventLoopGroupRegistry eventLoopGroupRegistry,EventLoopGroupFactory eventLoopGroupFactory,BeanContext beanContext,List invocationInstrumenterFactories,JsonMapper jsonMapper) --> new DefaultNettyHttpClientRegistry(HttpClientConfiguration defaultHttpClientConfiguration,HttpClientFilterResolver httpClientFilterResolver,LoadBalancerResolver loadBalancerResolver,NettyClientSslBuilder nettyClientSslBuilder,ThreadFactory threadFactory,MediaTypeCodecRegistry codecRegistry,EventLoopGroupRegistry eventLoopGroupRegistry,EventLoopGroupFactory eventLoopGroupFactory,BeanContext beanContext,List invocationInstrumenterFactories,[JsonMapper jsonMapper])
  	io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry] could not be loaded: Failed to inject value for parameter [jsonMapper] of class: io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry
```
2. I don't know which plugin uses `org.codehaus.groovy:groovy`, but now I see this exception with module `test-suite-groovy`:
```
> Could not resolve all dependencies for configuration ':test-suite-groovy:testCompileProtoPath'.
  The project declares repositories, effectively ignoring the repositories you have declared in the settings.
  You can figure out how project repositories are declared by configuring your build to fail on project repositories.
  See https://docs.gradle.org/7.5.1/userguide/declaring_repositories.html#sub:fail_build_on_project_repositories for details.
   > Could not find org.codehaus.groovy:groovy:.
     Required by:
         project :test-suite-groovy
```
I suspect that the problem is in the plugin 'com.google.protobuf' - it can't work on groovy 4

**Comment by altro3** [comment]
See https://github.com/micronaut-projects/micronaut-grpc/pull/612

**Pull request closed without merging**
