### PR TITLE
Upgrade libs. Fix versions for test suites

### PR DESCRIPTION
**Pull request by altro3**
Gradle 7.4.2
Protobuff 3.20.1
Grpc 1.46.0
Micronaut 3.4.3
MicronautTest 3.2.0
Spock 2.1-groovy-3.0

Fix versions in tests suites.

### CODE REVIEW

**Comment by alvarosanchez** [comment]
Ok great. Given the version changes, we would need to bump the minor version of micronaut-grpc. Let me see if there are more PRs that can be included, and I'll merge and release.

**Comment by graemerocher** [comment]
Graal test suites are failing :(

**Comment by altro3** [comment]
@graemerocher @alvarosanchez I fixed problem with kotlin-graalvm, but now I see new this:
```
> Task :test-suite-groovy:nativeCompile
[native-image-plugin] Using executable path: /opt/hostedtoolcache/graalvm-ce-java17-linux/22.0.0-2/x64/graalvm-ce-java17-22.0.0.2/bin/native-image
Fatal error: java.lang.NoClassDefFoundError: groovy/lang/GroovyObject
========================================================================================================================
GraalVM Native Image: Generating 'test-suite-groovy'...
========================================================================================================================
[1/7] Initializing...                                                                                   (16.4s @ 0.23GB)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)

> Task :test-suite-groovy:nativeCompile FAILED
> Task :test-suite-java:jar
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.oracle.svm.hosted.ImageClassLoader.forName(ImageClassLoader.java:285)
	at com.oracle.svm.hosted.ImageClassLoader.forName(ImageClassLoader.java:290)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:362)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:587)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:126)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:617)
Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyObject
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 18 more
Error: Image build request failed with exit status 1
```
I don't know how to fix this problem. All what I could find: https://github.com/oracle/graal/issues/1731 - but this is very old issue

**Comment by graemerocher** [comment]
the groovy test suite is not supposed to be included in the native tests, perhaps just disable the tasks for that project

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
